"""ilk sema - tum tablolar, kisitlar ve indeksler

Revision ID: 0001
Revises:
Create Date: 2026-09-13

Bu dosya `scripts/build_initial_migration.py` ile uretildi (bkz. betigin docstringi).
Elle duzenlenebilir; sonraki migration'lar alembic autogenerate ile uretilir.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_database_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Enum('usda', 'open_food_facts', 'manual', name='foodsource', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('search_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories_per_100g >= 0', name=op.f('ck_food_database_entry_calories_non_negative')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_food_database_entry_name_not_blank')),
    sa.CheckConstraint('protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0', name=op.f('ck_food_database_entry_macros_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_database_entry')),
    sa.UniqueConstraint('source', 'external_id', name='uq_food_source_external')
    )
    op.create_table('muscle_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name_tr', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=60), nullable=False),
    sa.Column('region', sa.Enum('front', 'back', name='bodyregion', native_enum=False, length=32), nullable=False),
    sa.Column('svg_id', sa.String(length=40), nullable=False),
    sa.Column('weekly_set_target', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(trim(slug)) > 0', name=op.f('ck_muscle_group_slug_not_blank')),
    sa.CheckConstraint('weekly_set_target > 0', name=op.f('ck_muscle_group_target_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_muscle_group')),
    sa.UniqueConstraint('slug', name=op.f('uq_muscle_group_slug'))
    )
    op.create_table('user',
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'unspecified', name='sex', native_enum=False, length=32), nullable=False),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activitylevel', native_enum=False, length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 80 AND 260', name=op.f('ck_user_height_sane')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.Enum('walking', 'running', 'cycling', 'swimming', 'sports', 'other', name='activitytype', native_enum=False, length=32), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_calories', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'ai_parsed', name='activitysource', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_min BETWEEN 1 AND 1440', name=op.f('ck_activity_log_duration_range')),
    sa.CheckConstraint('estimated_calories IS NULL OR estimated_calories >= 0', name=op.f('ck_activity_log_calories_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_activity_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_table('body_weight_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('body_fat_pct IS NULL OR body_fat_pct BETWEEN 1 AND 70', name=op.f('ck_body_weight_log_bodyfat_sane')),
    sa.CheckConstraint('weight_kg BETWEEN 20 AND 400', name=op.f('ck_body_weight_log_weight_sane')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_body_weight_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_weight_log')),
    sa.UniqueConstraint('user_id', 'date', name='uq_bodyweight_user_date')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_message_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_table('coach_report',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_coach_report_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_report')),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_coach_report_user_week')
    )
    op.create_table('exercise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('search_name', sa.String(length=120), nullable=False),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'machine', 'plate_loaded', 'smith_machine', 'cable', 'bodyweight', 'other', name='equipment', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_exercise_name_not_blank')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_exercise_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise')),
    sa.UniqueConstraint('owner_id', 'search_name', name='uq_exercise_owner_search')
    )
    op.create_table('injury_note',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('muscle_group_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(description)) > 0', name=op.f('ck_injury_note_description_not_blank')),
    sa.CheckConstraint('resolved_on IS NULL OR resolved_on >= started_on', name=op.f('ck_injury_note_resolved_after_start')),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], name=op.f('fk_injury_note_muscle_group_id_muscle_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_injury_note_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injury_note'))
    )
    op.create_table('nutrition_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('food_database_entry_id', sa.UUID(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype', native_enum=False, length=32), nullable=False),
    sa.Column('source_text', sa.String(length=1000), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_g > 0 AND quantity_g <= 10000', name=op.f('ck_nutrition_log_quantity_range')),
    sa.ForeignKeyConstraint(['food_database_entry_id'], ['food_database_entry.id'], name=op.f('fk_nutrition_log_food_database_entry_id_food_database_entry'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_nutrition_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_log'))
    )
    op.create_table('program',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('goal', sa.Enum('strength', 'hypertrophy', 'powerbuilding', 'general_fitness', name='programgoal', native_enum=False, length=32), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='programlevel', native_enum=False, length=32), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('cloned_from_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_template AND owner_id IS NULL) OR (NOT is_template AND owner_id IS NOT NULL)', name=op.f('ck_program_template_xor_owned')),
    sa.CheckConstraint('NOT (is_template AND is_active)', name=op.f('ck_program_template_not_active')),
    sa.CheckConstraint('NOT is_template OR source_name IS NOT NULL', name=op.f('ck_program_template_needs_source')),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name=op.f('ck_program_days_per_week_range')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_program_name_not_blank')),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['program.id'], name=op.f('fk_program_cloned_from_id_program'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_program_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program'))
    )
    op.create_table('soreness_checkin',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('muscle_group_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('level BETWEEN 0 AND 4', name=op.f('ck_soreness_checkin_level_range')),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], name=op.f('fk_soreness_checkin_muscle_group_id_muscle_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_soreness_checkin_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soreness_checkin')),
    sa.UniqueConstraint('user_id', 'date', 'muscle_group_id', name='uq_soreness_slot')
    )
    op.create_table('supplement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('dose', sa.String(length=80), nullable=True),
    sa.Column('schedule', sa.Enum('daily', 'training_days', 'rest_days', 'as_needed', name='supplementschedule', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_supplement_name_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplement_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplement')),
    sa.UniqueConstraint('user_id', 'name', name='uq_supplement_user_name')
    )
    op.create_table('exercise_muscle_map',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('muscle_group_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'secondary', name='musclerole', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_muscle_map_exercise_id_exercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], name=op.f('fk_exercise_muscle_map_muscle_group_id_muscle_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_muscle_map')),
    sa.UniqueConstraint('exercise_id', 'muscle_group_id', name='uq_exercise_muscle')
    )
    op.create_table('goal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('type', sa.Enum('bodyweight', 'body_fat_pct', 'lift_1rm', 'weekly_sessions', name='goaltype', native_enum=False, length=32), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('achieved_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'lift_1rm') = (exercise_id IS NOT NULL)", name=op.f('ck_goal_lift_goal_needs_exercise')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_goal_exercise_id_exercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_goal_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    op.create_table('pending_action',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('action_type', sa.Enum('log_food_item', 'log_activity', 'log_bodyweight', 'log_soreness', 'log_supplement', 'search_exercise_library', 'get_progression_suggestion', 'propose_program', 'propose_update', 'add_exercise_to_library', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='pendingactionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('chat_message_id', sa.UUID(), nullable=True),
    sa.Column('tool_use_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_entity_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending') = (resolved_at IS NULL)", name=op.f('ck_pending_action_resolved_matches_status')),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_message.id'], name=op.f('fk_pending_action_chat_message_id_chat_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_pending_action_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_action'))
    )
    op.create_table('program_day',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.CheckConstraint('length(trim(label)) > 0', name=op.f('ck_program_day_label_not_blank')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_program_day_program_id_program'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_day')),
    sa.UniqueConstraint('program_id', 'order_index', name='uq_program_day_order')
    )
    op.create_table('supplement_intake',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('supplement_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplement.id'], name=op.f('fk_supplement_intake_supplement_id_supplement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplement_intake_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplement_intake')),
    sa.UniqueConstraint('supplement_id', 'date', name='uq_intake_supplement_date')
    )
    op.create_table('action_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('action_type', sa.Enum('log_food_item', 'log_activity', 'log_bodyweight', 'log_soreness', 'log_supplement', 'search_exercise_library', 'get_progression_suggestion', 'propose_program', 'propose_update', 'add_exercise_to_library', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('proposed', 'executed', 'rejected', 'failed', name='actionresult', native_enum=False, length=32), nullable=False),
    sa.Column('detail', sa.String(length=2000), nullable=True),
    sa.Column('pending_action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pending_action_id'], ['pending_action.id'], name=op.f('fk_action_log_pending_action_id_pending_action'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_action_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    op.create_table('program_exercise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_day_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('target_sets', sa.SmallInteger(), nullable=False),
    sa.Column('target_rep_min', sa.SmallInteger(), nullable=False),
    sa.Column('target_rep_max', sa.SmallInteger(), nullable=False),
    sa.Column('technique', sa.Enum('straight', 'rir1', 'failure', 'rir1_to_failure', 'superset_failure', 'drop_set', 'myo_reps', name='intensitytechnique', native_enum=False, length=32), nullable=False),
    sa.Column('superset_group', sa.SmallInteger(), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('rest_seconds IS NULL OR rest_seconds BETWEEN 0 AND 900', name=op.f('ck_program_exercise_rest_range')),
    sa.CheckConstraint('target_rep_max BETWEEN target_rep_min AND 100', name=op.f('ck_program_exercise_rep_max_gte_min')),
    sa.CheckConstraint('target_rep_min BETWEEN 1 AND 100', name=op.f('ck_program_exercise_rep_min_range')),
    sa.CheckConstraint('target_sets BETWEEN 1 AND 20', name=op.f('ck_program_exercise_sets_range')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_program_exercise_exercise_id_exercise'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_day.id'], name=op.f('fk_program_exercise_program_day_id_program_day'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_exercise')),
    sa.UniqueConstraint('program_day_id', 'order_index', name='uq_program_exercise_order')
    )
    op.create_table('workout_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('program_day_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_deload', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_workout_session_completed_after_start')),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_day.id'], name=op.f('fk_workout_session_program_day_id_program_day'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_workout_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_session'))
    )
    op.create_table('personal_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('max_weight', 'max_reps', 'session_volume', 'estimated_1rm', name='prtype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workout_session_id', sa.UUID(), nullable=True),
    sa.Column('seen_by_user', sa.Boolean(), nullable=False),
    sa.CheckConstraint('value > 0', name=op.f('ck_personal_record_value_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_personal_record_exercise_id_exercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_personal_record_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], name=op.f('fk_personal_record_workout_session_id_workout_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_record'))
    )
    op.create_table('set_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('workout_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('rir', sa.SmallInteger(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('technique', sa.Enum('straight', 'rir1', 'failure', 'rir1_to_failure', 'superset_failure', 'drop_set', 'myo_reps', name='intensitytechnique', native_enum=False, length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('reps BETWEEN 1 AND 200', name=op.f('ck_set_log_reps_range')),
    sa.CheckConstraint('rir IS NULL OR rir BETWEEN 0 AND 10', name=op.f('ck_set_log_rir_range')),
    sa.CheckConstraint('set_number BETWEEN 1 AND 50', name=op.f('ck_set_log_set_number_range')),
    sa.CheckConstraint('weight_kg >= 0', name=op.f('ck_set_log_weight_non_negative')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_set_log_exercise_id_exercise'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_set_log_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], name=op.f('fk_set_log_workout_session_id_workout_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_log')),
    sa.UniqueConstraint('workout_session_id', 'exercise_id', 'set_number', name='uq_set_slot')
    )
    op.create_index('ix_food_database_entry_search_name', 'food_database_entry', ['search_name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index('ix_activity_log_user_id_date', 'activity_log', ['user_id', 'date'], unique=False)
    op.create_index('ix_body_weight_log_user_id_date', 'body_weight_log', ['user_id', 'date'], unique=False)
    op.create_index('ix_chat_message_user_id_created_at', 'chat_message', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_coach_report_user_id_week_start', 'coach_report', ['user_id', 'week_start'], unique=False)
    op.create_index('ix_exercise_owner_id', 'exercise', ['owner_id'], unique=False)
    op.create_index('ix_exercise_search_name', 'exercise', ['search_name'], unique=False)
    op.create_index('ix_injury_note_user_id_resolved_on', 'injury_note', ['user_id', 'resolved_on'], unique=False)
    op.create_index('ix_nutrition_log_user_id_date', 'nutrition_log', ['user_id', 'date'], unique=False)
    op.create_index('ix_program_owner_id', 'program', ['owner_id'], unique=False)
    op.create_index('uq_program_one_active_per_owner', 'program', ['owner_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_soreness_checkin_user_id_date', 'soreness_checkin', ['user_id', 'date'], unique=False)
    op.create_index('ix_exercise_muscle_map_muscle_group_id', 'exercise_muscle_map', ['muscle_group_id'], unique=False)
    op.create_index('ix_goal_user_id_type', 'goal', ['user_id', 'type'], unique=False)
    op.create_index('ix_pending_action_user_id_status', 'pending_action', ['user_id', 'status'], unique=False)
    op.create_index('ix_supplement_intake_user_id_date', 'supplement_intake', ['user_id', 'date'], unique=False)
    op.create_index('ix_action_log_user_id_created_at', 'action_log', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_program_exercise_exercise_id', 'program_exercise', ['exercise_id'], unique=False)
    op.create_index('ix_workout_session_user_id_started_at', 'workout_session', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_personal_record_user_id_exercise_id_type', 'personal_record', ['user_id', 'exercise_id', 'type'], unique=False)
    op.create_index('ix_set_log_user_id_exercise_id', 'set_log', ['user_id', 'exercise_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_database_entry_search_name', table_name='food_database_entry')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index('ix_activity_log_user_id_date', table_name='activity_log')
    op.drop_index('ix_body_weight_log_user_id_date', table_name='body_weight_log')
    op.drop_index('ix_chat_message_user_id_created_at', table_name='chat_message')
    op.drop_index('ix_coach_report_user_id_week_start', table_name='coach_report')
    op.drop_index('ix_exercise_owner_id', table_name='exercise')
    op.drop_index('ix_exercise_search_name', table_name='exercise')
    op.drop_index('ix_injury_note_user_id_resolved_on', table_name='injury_note')
    op.drop_index('ix_nutrition_log_user_id_date', table_name='nutrition_log')
    op.drop_index('ix_program_owner_id', table_name='program')
    op.drop_index('uq_program_one_active_per_owner', table_name='program', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_soreness_checkin_user_id_date', table_name='soreness_checkin')
    op.drop_index('ix_exercise_muscle_map_muscle_group_id', table_name='exercise_muscle_map')
    op.drop_index('ix_goal_user_id_type', table_name='goal')
    op.drop_index('ix_pending_action_user_id_status', table_name='pending_action')
    op.drop_index('ix_supplement_intake_user_id_date', table_name='supplement_intake')
    op.drop_index('ix_action_log_user_id_created_at', table_name='action_log')
    op.drop_index('ix_program_exercise_exercise_id', table_name='program_exercise')
    op.drop_index('ix_workout_session_user_id_started_at', table_name='workout_session')
    op.drop_index('ix_personal_record_user_id_exercise_id_type', table_name='personal_record')
    op.drop_index('ix_set_log_user_id_exercise_id', table_name='set_log')
    op.drop_table('set_log')
    op.drop_table('personal_record')
    op.drop_table('workout_session')
    op.drop_table('program_exercise')
    op.drop_table('action_log')
    op.drop_table('supplement_intake')
    op.drop_table('program_day')
    op.drop_table('pending_action')
    op.drop_table('goal')
    op.drop_table('exercise_muscle_map')
    op.drop_table('supplement')
    op.drop_table('soreness_checkin')
    op.drop_table('program')
    op.drop_table('nutrition_log')
    op.drop_table('injury_note')
    op.drop_table('exercise')
    op.drop_table('coach_report')
    op.drop_table('chat_message')
    op.drop_table('body_weight_log')
    op.drop_table('activity_log')
    op.drop_table('user')
    op.drop_table('muscle_group')
    op.drop_table('food_database_entry')
    # ### end Alembic commands ###
